create table if not exists public.market_signals (
    signal_id uuid primary key,
    detected_at timestamp not null,
    instrument_id text,
    ticker text not null,
    class_code text,
    alias text,
    source_event_type text,
    signal_type text not null,
    severity integer not null,
    metric_value numeric,
    baseline_value numeric,
    z_score numeric,
    window_seconds integer,
    summary text,
    payload_json jsonb not null default '{}'::jsonb
);

insert into public.market_signals (
    signal_id,
    detected_at,
    instrument_id,
    ticker,
    class_code,
    alias,
    source_event_type,
    signal_type,
    severity,
    metric_value,
    baseline_value,
    z_score,
    window_seconds,
    summary,
    payload_json
) values
(
    '11111111-1111-1111-1111-111111111111',
    now() - interval '5 minutes',
    'TQBR:SBER',
    'SBER',
    'TQBR',
    'SBER',
    'last_price',
    'price_jump',
    3,
    285.40,
    277.10,
    8.50,
    300,
    'SBER резко отклонился от краткосрочного базового уровня.',
    '{"quality_score": 92, "delivery_status": "delivered", "delivery_reason": "high_quality_realtime_signal", "delivery_rule": "realtime", "delivery_channel": "telegram"}'::jsonb
),
(
    '22222222-2222-2222-2222-222222222222',
    now() - interval '10 minutes',
    'TQBR:GAZP',
    'GAZP',
    'TQBR',
    'GAZP',
    'last_price',
    'volume_spike',
    3,
    184.20,
    176.50,
    7.20,
    300,
    'GAZP дал сильный всплеск объема, но правило доставки ограничило сигнал.',
    '{"quality_score": 88, "delivery_status": "suppressed", "delivery_reason": "risk_rule_cooldown", "delivery_rule": "cooldown", "delivery_channel": "none"}'::jsonb
),
(
    '33333333-3333-3333-3333-333333333333',
    now() - interval '16 minutes',
    'TQBR:LKOH',
    'LKOH',
    'TQBR',
    'LKOH',
    'last_price',
    'trend_break',
    2,
    7210.00,
    7145.00,
    4.40,
    600,
    'LKOH вышел за границу внутридневного тренда.',
    '{"quality_score": 71, "delivery_status": "suppressed", "delivery_reason": "manual_review_required", "delivery_rule": "manual_review", "delivery_channel": "admin_only"}'::jsonb
),
(
    '44444444-4444-4444-4444-444444444444',
    now() - interval '22 minutes',
    'TQBR:FIXR',
    'FIXR',
    'TQBR',
    'FIXR',
    'spread',
    'spread_widening',
    1,
    2.80,
    1.50,
    2.20,
    300,
    'FIXR расширил спред, но сигнал слабый.',
    '{"quality_score": 45, "delivery_status": "suppressed", "delivery_reason": "low_quality", "delivery_rule": "quality_gate", "delivery_channel": "none"}'::jsonb
)
on conflict (signal_id) do nothing;
